### ISSUE TITLE
Keys being set in a map even with pickOnlySomeKeys set to true

### ISSUE THREAD

**Issue by faizanabidnaqvi** [firecmsco/firecms#276]
Hi there

Found this minor issue. I have a map field that has several properties which are also map fields; the parent and nested map fields both have 'pickOnlySomeKeys' set to true. 

When I save such an entity, without touching any part of the map or the nested map, the nested map fields are added as empty objects.

Here is the schema for such a field:
```
map: {
    title: "map",
    dataType: "map",
    config: {
        pickOnlySomeKeys: true
    },
    properties: {
        nestedmap1: {
            title: "nestedmap1",
            dataType: "map",
            config: {
                pickOnlySomeKeys: true
            },
            properties: {
                boolfield: {
                    title: "field",
                    dataType: "boolean",
                  },
            }
        },
        nestedmap2: {
            title: "nestedmap1",
            dataType: "map",
            config: {
                pickOnlySomeKeys: true
            },
            properties: {
                boolfield: {
                    title: "field",
                    dataType: "boolean",
                  },
            }
        }
    }
},
```

When the entity is saved without touching any of the fields, in the firestore doc the following fields will appear:
```
map: {
    nestedmap1: {},
    nestedmap2: {},
}
```

I believe these should not be set when pickOnlySomeKeys was set to true. Infact, if none of these fields are touched, I expect the keys not to be appear in the doc at all.

**Comment by fgatti675** [comment]
Closing this one since it does not apply anymore
