### ISSUE TITLE
Dynamic map

### ISSUE THREAD

**Issue by dvird** [firecmsco/firecms#284]
Is there way for dynamic map?

i want for example to add to "product" field of "members"
the field will be map of userid to role
{"adafewr324asfas":"admin}

**Comment by dvird** [comment]
today we can only build a map with default keys
for example:
`
publisher: {
            title: "Publisher",
            description: "This is an example of a map property",
            dataType: "map",
            properties: {
                name: {
                    title: "Name",
                    dataType: "string"
                },
                external_id: {
                    title: "External id",
                    dataType: "string"
                }
            }
        }
`

i want to put dynamic keys on the cms, i want the key will be user id , and value will be rule

**Comment by warrenrhodes** [comment]
I have the same problem. I have a restaurant model `restaurants:{ restaurantTables : Record<string, RestaurantTable>}` and I can't represent it in the CMS. because the CMS doesn't allow to define a property as a key

**Comment by fgatti675** [comment]
Hi guys, this feature is not planned in the near future.
We are happy to receive PRs though, and if this is important for your business we are also happy to discuss implementing it as a consulting project, you can reach us at hello@firecms.co

**Comment by warrenrhodes** [comment]
@fgatti675 I was able to work around this by creating a custom preview and a custom field. Editing, updating and adding work fine, except for deleting. 
eg: `const tables : Record<String, Table> = { 'tableId_1' : {name: 'Africa'}, 'tableId_2' : {name: 'Europe'}, 'tableId_3' : {name: 'Asia'}} ; 
delete the tables [tableId_3]; delete the tables [tableId_2];``.
we expect on the database ` tables: {'tableId_1': {name: 'Africa'}} ` which is not the case. In fact, the database is not updated but when we print the `values` contained `onPreSave` and `onSaveSuccess` callback function, they contain the correct information but the database is not updated and the preview widget contains this map ` tables: {'tableId_1': {name: 'Africa'}, 'tableId_1': {name: 'Europe'}} `

**Comment by fgatti675** [comment]
Hi guys, it is now possible to add arbitrary key-value data to map properties, feed free to try out!

**Comment by muhamed-didovic** [comment]
@warrenrhodes found solution for delete, care to share part of you code I am in same problem, thanks
