### ISSUE TITLE
Add a dropdown filter to reference properties

### ISSUE THREAD

**Issue by jabelone** [firecmsco/firecms#314]
Hi there,

I have a collection that makes use of a reference property to another collection (so I can use a dynamic list of categories). This seems to work well, but I don't get a dropdown list for the filter at the top of the column like I would by using the `enumValues: []` config option.

Essentially, given the following property:

```
category: {
            title: "Category2",
            validation: { required: true },
            dataType: "reference",
            path: "cms-categories",
            previewProperties: ["name"],
        },
```

I'd like to see a dropdown filter like pictured on the left most category column in the picture below.

<img width="581" alt="image" src="https://user-images.githubusercontent.com/9560876/168731459-f42293c3-8cc5-4106-8eb6-aebea6eea295.png">

Alternatively, it would be nice to add a dropdown filter (exactly as per above screenshot) above the table at the top of the page rather than at the top of the column. The use case being I'd like for other less tech savvy users to have a nice big obvious dropdown at the top of the page so they can easily see which "category" they are currently viewing/editing entities from. I know this is a bit niche, so the first request above would be awesome just by itself!

**Comment by jabelone** [comment]
Thanks so much! I've just updated the title/description so it's a little more like a feature request than a question :)

**Comment by fgatti675** [comment]
This was added a few versions ago!
