### ISSUE TITLE
FireCMS opens same page after logout -> login

### ISSUE THREAD

**Issue by GoldenSoju** [firecmsco/firecms#389]
Hi! First of all thanks for all your work!

My problem:
When I logout and login again, the system opens the same page which was last visited prior to logout.
That also happens when I login with a different user.
This behaviour can also be tested in the demo.

Not sure why, but I guess the navigation context saves the path?
If that is intended behaviour, I was wondering on how to disable it.

**Comment by fgatti675** [comment]
This is super late, but will be available after versions `3.0.0-canary.77` and `3.0.0-beta.8`
