### ISSUE TITLE
Uploading Data from excel or csv

### ISSUE THREAD

**Issue by bassem21** [firecmsco/firecms#408]
Hello, how about adding support to add data to firestore collection through uploading an excel sheet or csv?
Same as downloading data in an csv format
Thanks for the awesome work 🙌

**Comment by fgatti675** [comment]
Thank you @bassem21 
This is not currently in the pipeline. We have added a new label looking for a sponsor, so if someone contributes, we will prioritise it. PRs are also welcome!

**Comment by fgatti675** [comment]
This is implemented and working in the latest version :)
