### ISSUE TITLE
[maybe bug] incorrect collection path while using alias + subcollection

### ISSUE THREAD

**Issue by zarifabdalimov** [firecmsco/firecms#439]
Hello,

I think there is bug when I am using an alias with subcollections... when I tried to configure subcollection I get an "insufficient permission error". I go to check my firestore rules and everything seems ok... then I tried to remove an alias for parent collection and it starts working correctly 🤔 is this bug or my misconfiguration? 

Thank you

P.S. sorry if duplicate, I didn't find the answer

collection setup:

````
import { buildCollection } from '@camberi/firecms'

const technologies = buildCollection<{
  name: string
  type: 'language' | 'programmingSkill' | 'technology'
  patterns?: string[]
}>({
  defaultSize: 'xs',
  exportable: false,
  selectionEnabled: false,
  initialFilter: {
    type: [ '==', 'technology' ],
  },
  name: 'Technologies',
  singularName: 'Technology',
  group: 'Tags',
  description: 'Technologies documents ...',
  path: 'tags',
  // alias: 'technologies', <----- if uncomment it then it fails 😞
  icon: 'Code',
  permissions: ({ authController }) => ({
    edit: true,
    create: true,
    // we have created the roles object in the navigation builder
    delete: false,
  }),
  subcollections: [
    {
      name: "NER",
      path: 'ner',
      permissions: {
        edit: true,
        create: true,
      },
      properties: {
        patterns: {
          name: 'NER Patterns',
          dataType: 'array',
          of: {
            dataType: 'string',
          },
        }
      }
    }
  ],
  properties: {
    name: {
      name: 'Name',
      validation: { required: true },
      dataType: 'string',
    },
    type: {
      name: 'Type',
      // hideFromCollection: true,
      validation: { required: true },
      dataType: 'string',
      enumValues: [
        {
          label: 'Language',
          id: 'language',
        },
        {
          label: 'Programming skill',
          id: 'programmingSkill',
        },
        {
          label: 'Technology',
          id: 'technology',
        },
      ],
    },
  },
})

export {
  technologies,
}
```

**Comment by fgatti675** [comment]
Hi @zarifabdalimov 
Could you provide a minimal example where this happens??
Best

**Comment by valguzin55** [comment]
i faced the same error
`export default function getCollections(user:any)  {
    const addSales = salesCollection.properties.products = {
        dataType: "array",
        name: "Продукты",
        description: "Продукты купленные пользоваетелем",
        of: {
            dataType: "reference",
            path: "shops/dan/products"
        }
    }
    const salesProperties = salesCollection.properties
    salesProperties.products = addSales
    return [
        buildCollection(usersCollection),
        buildCollection({...productCollection, path: '/shops/'+user+productCollection.path}),
        buildCollection({...infoCollection, path: '/shops/'+user+infoCollection.path}),
        buildCollection({...salesCollection, path: '/shops/'+user+salesCollection.path, properties: salesProperties})
        
    ]
}`
my firebase screen
<img width="1154" alt="Снимок экрана" src="https://user-images.githubusercontent.com/41577362/216813984-2cfa3007-be98-4ffa-88a9-f5c84e7dff4e.png">

**Comment by valguzin55** [comment]
> i faced the same error
> 
> ```
>     const addSales = salesCollection.properties.products = {
>        dataType: "array",
>         name: "Продукты",
>        description: "Продукты купленные пользоваетелем",
>         of: {
>             dataType: "reference",
>             path: "/shops/dan/products"
>         }
>     }
>     const salesProperties = salesCollection.properties
>     salesProperties.products = addSales
>     return [
>         buildCollection(usersCollection),
>         buildCollection({...productCollection, path: '/shops/'+user+productCollection.path}),
>         buildCollection({...infoCollection, path: '/shops/'+user+infoCollection.path}),
>         buildCollection({...salesCollection, path: '/shops/'+user+salesCollection.path, properties: salesProperties})
>         
>     ]
> }
> ```
> 
> my firebase screen <img alt="Снимок экрана" width="1154" src="https://user-images.githubusercontent.com/41577362/216813984-2cfa3007-be98-4ffa-88a9-f5c84e7dff4e.png"> project <img alt="Снимок экрана" width="925" src="https://user-images.githubusercontent.com/41577362/216814085-b758bb69-3bdb-425f-9f8e-e64d296b147d.png">

solved the problem like this
```

export default function getCollections(user:any)  {
   
    const addSales = salesCollection.properties.products = {
        dataType: "array",
        name: "Продукты",
        description: "Продукты купленные пользоваетелем",
        of: {
            dataType: "reference",
             path: "/shops/dan/products",
            
        }
    }
    const salesProperties = salesCollection.properties
    salesProperties.products = addSales
    return [
        buildCollection(usersCollection),
        buildCollection({...productCollection, path: 'shops/'+user+productCollection.path}),
        buildCollection({...infoCollection, path: 'shops/'+user+infoCollection.path}),
        buildCollection({...salesCollection, path: 'shops/'+user+salesCollection.path, properties: salesProperties})
        
    ]
}
```
i only delete prefix path '/' because in navigation context save path without / and all worked

**Comment by fgatti675** [comment]
Thanks for this!
V3 uses ids instead of paths or aliases for resolutions, so this one does not apply anymore
