### ISSUE TITLE
Unable to drag&move video field in array dataType field

### ISSUE THREAD

**Issue by n-kulic** [firecmsco/firecms#456]
### What is the current behavior?
Attempting to drag and move the video field in an array dataType field causes the video to reload and cancels the draggable process (it returns to its original position).

https://user-images.githubusercontent.com/94164339/213546619-da0daf9d-1845-4c17-b632-0e7437974563.mp4

### What is the expected behavior?
Drag, move and drop video field to desired position **in array dataType**

### Package versions used
- React: 18.2.0
- ReactDOM: 18.2.0
- firecms: 2.0.0-beta.1

**Comment by nickvelloff** [comment]
https://user-images.githubusercontent.com/885369/223561216-27ac6098-9c64-400a-bcba-74472088d125.mov

Same. Thanks!

**Comment by fgatti675** [comment]
Hi guys, sorry for the late response.
This has been fixed and will be released in versions after `3.0.0-canary.78` and `3.0.0-beta-8`
