### ISSUE TITLE
Catastrophic fail if no storage found

### ISSUE THREAD

**Issue by JoachimKoenigslieb** [firecmsco/firecms#470]
I i try to load a project using version "firecms": "2.0.0-beta.2", I get a white screen and this error in the console:

<img width="574" alt="image" src="https://user-images.githubusercontent.com/25743536/218075041-390c2def-79c7-47d2-9f1e-2f44f2759d8d.png">

I have personally hacked together something for dev purposes at https://github.com/Camberi/firecms/commit/d8ecae63b2ff5c6bb2646464fda77312c655a1db which fixes my problem. This allows me to open and use the project without any issues noticed. (I'm sure storage wouldnt work...) This fix is probably not good for you guys in production?

If you would like, I can create pull requests with any changes needed to land this fix.

Would really love a fix so I dont have to depend on a forked version. Love the repo!

Joachim

**Comment by fgatti675** [comment]
Thanks a lot Joachin! a PR would be awesome :)

**Comment by carlos-algms** [comment]
I do have the `Storage` enabled, and I'm still getting the same error, saying that the `Service storage is not available`.

 
![image](https://github.com/firecmsco/firecms/assets/4634613/cc2f5374-4fe7-4948-8d5e-00d3b6374e0f)

**Comment by fgatti675** [comment]
This does not apply anymore to the latest version

**Comment by zirhoo** [comment]
This was due to multiple versions of firebase npm package being installed and used

When I inspected yarn.lock files, I found 10 and 9 versions of firebase are installed.

I updated package.json


```
    "firebase": "^10",
```

and installed the package again. 

it works now.

FYI
