### ISSUE TITLE
The scrollbar messes up the alignment of icons

### ISSUE THREAD

**Issue by SeeringPhil** [firecmsco/firecms#481]
When the navigation bar has too many icons or the screen is too small, the scrollbar is shown and the icons are moved a little bit. 

This movement is not the same for the logo, and that makes it so the hamburger button (three horizontal lines), the logo, and the collection icons are not aligned anymore and this looks a little bit off. 

https://user-images.githubusercontent.com/9097313/226418551-08679837-b99f-4e2b-abc0-f0db861f3be4.mov

Proposed solutions: 
- Hide the scrollbar, I think people this is a case where people will know intuitively that they can scroll since there would be icons fading down + it would give a cleaner look (Maybe this could be an option?)
- Make sure the logo is centered when the scrollbar is shown so that everything aligns

**Comment by fgatti675** [comment]
This does not apply anymore to the latest version
