### ISSUE TITLE
Data enhancement -> not able to build locally 

### ISSUE THREAD

**Issue by SeeringPhil** [firecmsco/firecms#482]
We are now unable to complete installation of dependencies when cloning the project since package.json refers to workspace:data_enhancement. 

![image](https://user-images.githubusercontent.com/9097313/226429423-152aa336-0876-42bb-b87e-eb667df42917.png)

For now, I'll start new PR branches from a previous state in the git history.

**Comment by fgatti675** [comment]
Thank you, we have cleaned up the code so it works out the box after cloning the project
