### ISSUE TITLE
Custom entity view tabs error

### ISSUE THREAD

**Issue by rwverbakel** [firecmsco/firecms#484]
When adding a custom entity view to a collection, I get the error:

Tabs.js:314 MUI: The `value` provided to the Tabs component is invalid.
The Tab with this `value` ("0") is not part of the document layout.
Make sure the tab item is present in the document or that it's not `display: none`.

This error appears only on larger screen sizes, when the custom view is side-by-side with the main record.

**Comment by fgatti675** [comment]
This does not apply anymore to the latest version, since it migrated to tailwind.
Thanks!
