### ISSUE TITLE
Collection Group Custom Field duplicates the data

### ISSUE THREAD

**Issue by ivanandresdiaz** [firecmsco/firecms#506]
Hello,
This is a small bug. I am using a collection Group of subcollections, you know, the subcollection is a second level. I hit, the bottom save,
![image](https://github.com/firecmsco/firecms/assets/71022077/ac05c53b-caf2-41d4-8b43-a459d4292fb2)

  and it created a document in the  top level. collection 

![Imagen22](https://github.com/firecmsco/firecms/assets/71022077/e2201fb2-4f9e-445c-bf87-864e0c827082)

this bug is only when I do inline editing. 

`   collectionGroup: true,
  properties: {
    props: {
      dataType: "string",
      name: "Parametros del video",
      Field: Props,
    },`

**Comment by fgatti675** [comment]
Closing this as it was referring to a previous version. Feel free to open again if it resurfaces
