### ISSUE TITLE
Need to update a parent collection based on sub collection data. How to do that ?

### ISSUE THREAD

**Issue by johnvinosh** [firecmsco/firecms#510]
For a blog app, I have sub collection for each locale. I want to update a slug on parent collection based on blog title on sub locale collection. How to achieve this using callbacks ?

**Comment by fgatti675** [comment]
Super late but:
In the callback you have a `context` and you can access the `dataSource` from there. You can use it to update data as you see fit.
Or you could achieve the same using a cloud function
