### ISSUE TITLE
[regression bug] Default optional image URL is stored as empty string instead of `null`

### ISSUE THREAD

**Issue by SimpleCreations** [firecmsco/firecms#513]
### Bug description

**Marked this as a regression because the issue was not present in [`2.0.0-beta.4`](https://github.com/firecmsco/firecms/releases/tag/v2.0.0-beta.4)**

An empty string is not a valid URL, so it shouldn't be assigned to a field intended to store a URL. If the image field is optional, `null` should be used to indicate a lack of image.

### Steps to reporduce

* Create a collection with an optional image field
* Add a new document without filling in the image field

### Expected behavior

* The image field value is stored in Firestore as `null`

### Actual behavior

* The image field value is stored in Firestore as `""`

**Comment by fgatti675** [comment]
Fixed in version 2.0.5 :)

**Comment by SimpleCreations** [comment]
Hi @fgatti675! I'm not sure if it's related, but I still have the following issue with optional images: if I attach a file, and then delete it right away using the "minus" button, the "save" button becomes greyed out even though the form is filled correctly (the image is optional).
