### ISSUE TITLE
Any documentation on how to write a custom plugin?

### ISSUE THREAD

**Issue by axshae** [firecmsco/firecms#514]
Firstly, thank you for your hard work on this project. It has been a valuable tool for me, and I am grateful for your contributions to the open source community. 

I'm really curious about the plugin system and how it works with the CMS, like the "ChatGPT" plugin mentioned in the docs. 

Is there any documentation available for writing a custom plugin?

**Comment by fgatti675** [comment]
Hi @axshae 
Thanks a lot for your interest!
Right now this functionality is only meant for in-house developed plugins. There are some internal APIs exposed but they are not stable and only allow making the changes that were needed by our plugins, so it is pretty restricted.
If you are still interested in developing something, I would love to hear a bout your use case, so I can tell you how to proceed!

**Comment by fgatti675** [comment]
I am closing this issue for now since plugins are not planned for the near future.
Please reach us at Discord if you are still interested!
