### ISSUE TITLE
Missing dependency in useCallback breaks text search

### ISSUE THREAD

**Issue by Ziiiiiiiiit** [firecmsco/firecms#515]
In firebase_app/hooks/useFirestoreDataSource.ts, the useCallback of performTextSearch lacks the textSearchController as a dependency, This breaks text search for me as I am dependent on the textSearchController being able to change!

**Comment by fgatti675** [comment]
Thank you @Ziiiiiiiiit , releasing a fix soon :)

**Comment by fgatti675** [comment]
Fixed in version 2.0.5 :)

**Comment by Ziiiiiiiiit** [comment]
Thank you! I can confirm that it now works perfectly! :)
