### ISSUE TITLE
Is there a way to disable the option to create users when there is none with the provided email?

### ISSUE THREAD

**Issue by lucasmonteiro58** [firecmsco/firecms#520]
I would like to disable the option to create a user here when the login method is 'password'. When there is no user with the provided email, it displays the message 'No user found with that email. Pick a password to create a new account.' I want to deactivate this and only keep the users I created through the Firebase panel. How can I do that?

![screenshot](https://i.ibb.co/Qn38GY9/2023-07-13-19-40-09-Arroxa-lab-Fire-CMS.png)

**Comment by fgatti675** [comment]
Hi @lucasmonteiro58 
I am afraid it is not possible ATM, but we keep this as a feature request.

**Comment by fgatti675** [comment]
Thank you @richardszegh 
We should probably make it easier to implement this behaviour
