### ISSUE TITLE
Multiple Read Write when text field updated

### ISSUE THREAD

**Issue by dorianbucknor** [firecmsco/firecms#527]
When a textfiled is update (inline editing) it fires multiple reads and writes on firestore. Seems like it is saved onChange instead of onBlur. OnChange will fire multilpe updates when writing causing read write quota for firebase to sky rocket.

Recommending to change to OnBlur

**Comment by fgatti675** [comment]
Hi, this is not saved on change nor onblur, it is using a debounced value with a timeout
