### ISSUE TITLE
CMS Freezes randomly in Microsoft Edge - Chrome seems fine.

### ISSUE THREAD

**Issue by bryzen** [firecmsco/firecms#528]
When CMS freezes, unable to click on anything and must refresh. 
Tried disabling all extensions and clearing browser caches but no success.   Happens a lot when opening and closing the edit screens multiple times Or leaving an image field empty with no file attached.    I have been able to replicate on two computers.

**Comment by fgatti675** [comment]
Thank you bryzen, I didn't manage to reproduce. Is there any output in the console?

**Comment by bryzen** [comment]
![image](https://github.com/firecmsco/firecms/assets/24556402/911c7da2-4365-4ae1-9294-02e38dbee4f6)
This is the only thing I am seeing in console.  I was able to reproduce the freezing again even on the demo site(https://demo.firecms.co/).

**Comment by fgatti675** [comment]
I was unable to reproduce in V3, feel free to reopen if it still happens!
