### ISSUE TITLE
Can't Reproduice the key/value feature

### ISSUE THREAD

**Issue by warrenrhodes** [firecmsco/firecms#529]
Hello. Thanks for the Key/value feature, I've been looking forward to it. But I can't reproduce it. The following documentation 
https://firecms.co/docs/properties/fields/key_value isn't explicit enough on this subject and the example code given doesn't match the feature. Could you please give me an example code.

**Comment by fgatti675** [comment]
Sorry, the documentation is wrong, fixing it
