### ISSUE TITLE
How do I get current user id in a property?

### ISSUE THREAD

**Issue by virendrapalsingh** [firecmsco/firecms#531]
properties: {
createdBy: {
            name: "Created By",
            dataType: "string",
            defaultValue:  "Want to automaticaly add user id here",
            readOnly: true,
        }
}

**Comment by fgatti675** [comment]
https://firecms.co/docs/collections/dynamic_collections

**Comment by virendrapalsingh** [comment]
How do I use EntityCollectionsBuilder with existing EntityCollection?
