### ISSUE TITLE
Attempted import error: 'getCountFromServer' is not exported from 'firebase/firestore' (imported as 'sl').

### ISSUE THREAD

**Issue by warrenrhodes** [firecmsco/firecms#532]
I get the error `Attempted import error: 'getCountFromServer' is not exported from 'firebase/firestore' (imported as 'sl').` when building a project with fireCms instead of @Camberi/firecms.

**Comment by fgatti675** [comment]
Hi Warren, make sure you are using the latest Firestore library, that method was added in recent versions

**Comment by warrenrhodes** [comment]
I used the same version of firebase that firecms uses, it didn't work, but after updating to version 9.23, it works fine.
