### ISSUE TITLE
Run the test on  firecms project failed

### ISSUE THREAD

**Issue by warrenrhodes** [firecmsco/firecms#533]
<img width="788" alt="Screenshot 2023-08-08 at 13 10 01" src="https://github.com/firecmsco/firecms/assets/46690709/30fd5c5f-abe9-4d46-81f0-4450032366a4">

NB: I use the same version of react, firebase etc... as fireCms

**Comment by fgatti675** [comment]
Closing this one since it does not apply to the latest version
