### ISSUE TITLE
2.0.1 breaks CustomEntityViews (shows blank)

### ISSUE THREAD

**Issue by suecom** [firecmsco/firecms#534]
Breaks CustomEntityViews - they are blank! Reverting 2.0.0, the contents are returned :-)

**Comment by suecom** [comment]
The problem was actually introduced in 2.0.1.

**Comment by fgatti675** [comment]
Thank you @suecom,
We didn't get any reports of this. I suspect it may be related to your setup. 
Could you tell me the output of the console?

**Comment by suecom** [comment]
Try attachment again!

￼

Allister
ΠΟωaττ - finding value in IoT data
+44 7729 175634
http://www.nowatt.com <http://www.nowatt.com/>

**Comment by fgatti675** [comment]
Sorry man, it is not displayin anything

**Comment by suecom** [comment]
So with 2.0.4 you see the alt3 view?

Allister
ΠΟωaττ - finding value in IoT data
+44 7729 175634
http://www.nowatt.com <http://www.nowatt.com/>

**Comment by suecom** [comment]
With 2.0.0:

￼

￼



With 2.0.1:

￼


￼


Allister
ΠΟωaττ - finding value in IoT data
+44 7729 175634
http://www.nowatt.com <http://www.nowatt.com/>

**Comment by suecom** [comment]
Should also mention using Node 18.13.0

Allister
ΠΟωaττ - finding value in IoT data
+44 7729 175634
http://www.nowatt.com <http://www.nowatt.com/>

**Comment by fgatti675** [comment]
I meant your attachments are not being displayed correctly on Gihub,
can you upload them from within the website (not via email)?

**Comment by suecom** [comment]
With 2.0.1
<img width="364" alt="PastedGraphic-2" src="https://github.com/firecmsco/firecms/assets/11705833/653f7497-fb21-4614-bab4-41ab47039a7d">
<img width="640" alt="PastedGraphic-4" src="https://github.com/firecmsco/firecms/assets/11705833/b48ada94-5139-4425-9b57-0be132468d11">
Going back to 2.0.0:
<img width="337" alt="PastedGraphic-3" src="https://github.com/firecmsco/firecms/assets/11705833/9b06e46f-ded1-41be-b831-b99ed07787f7">
<img width="640" alt="PastedGraphic-1" src="https://github.com/firecmsco/firecms/assets/11705833/ddd3b691-f569-4323-8d40-c032bec88271">

**Comment by suecom** [comment]
I closed the issue by mistake! Did you get the project (v4) to demonstrate this?

function SamplePlanView2({ collection, entity, modifiedValues }: EntityCustomViewParams<Plan>) {
    return (
        <Box>
            <Container
                maxWidth={"sm"}
                sx={{
                    mt: 4,
                    justifyItems: "center",
                    display: "flex",
                    flexDirection: "column"
                }}
            >
                <Typography 
                    variant={"h3"}
                    sx={{
                        marginTop: "40px",
                        marginBottom: "20px"
                    }}
                >
                    'This is: {entity?.values.name}'
                </Typography>
            </Container>
        </Box>
    );
}

export const planCollection = buildCollection<Plan>({
    name: "Plans",
    singularName: "Plan",
    description: "Drinking plans",
    path: "consumed",
    icon: "NoDrinks",
    group: "Drink",
    views: [
        {
            name: "Alt3",
            path: '.',
            Builder: SamplePlanView2
        }
    ],
    …


Allister
ΠΟωaττ - finding value in IoT data
+44 7729 175634
http://www.nowatt.com <http://www.nowatt.com/>

**Comment by fgatti675** [comment]
Please, the console output of the browser

**Comment by suecom** [comment]
<img width="2025" alt="image" src="https://github.com/firecmsco/firecms/assets/11705833/27977851-5560-4cd2-8c71-2ced8ca6423c">

**Comment by fgatti675** [comment]
Man I can't reproduce this, your sample code was very broken.
After fixing it, it seems to be fine:
```
    return (
        <Box>
            <Container
                maxWidth={"sm"}
                sx={{
                    mt: 4,
                    justifyItems: "center",
                    display: "flex",
                    flexDirection: "column"
                }}>

                <Typography
                    variant={"h3"}
                    sx={{
                        marginTop: "40px",
                        marginBottom: "20px"
                    }}>

                    {`This is: ${entity?.values.name}`}
                </Typography>
            </Container>
        </Box>
    )
        ;
        ```

**Comment by fgatti675** [comment]
Also, you should probably not use "." as a path, it may interfere with routing

**Comment by suecom** [comment]
Thanks for looking at this - I assume I'm not the only one using CustomEntityViews, so must be me :-(

What is certain, is the page content (thanks for the correction), nor the path is behind the change in behaviour between 2.0.0 and 2.0.1. BTW, what should the path be is a custom entity view? If I put '/consumed' (what I expect), the address bar is: http://localhost:5173/c/consumed/0qv7roJXEcBHpPNRFRkf//consumed. That's why I used '.' - to at least keep the path showing correctly.

The project is at: https://github.com/suecom/v4 

Very basic, and package.json is set to use the latest firecms package, so you'll see the problem immediatly.
