### ISSUE TITLE
reference with multiple collections

### ISSUE THREAD

**Issue by ciriousjoker** [firecmsco/firecms#545]
We have a `someRef` property that can be either `somecol1/docid` or `somecol2/docid`.

We want to preview those documents based on a common map property "name" (specifically "name.en").

Current workaround:

- Create onFetch callback
- Spread `someRef` into `someRef1` and `someRef2`
- Mark these as readonly
- Display the fake properties as separate columns

Solution works but is obviously not optimal. I can't suggest a better solution though aside from "make it easier somehow" :D

**Comment by fgatti675** [comment]
Mmm, you should be able to customise the preview properties of a ref: https://firecms.co/docs/properties/config/reference#previewproperties

I think you can customise those by using a PropertyBuilder, based on the value:
https://firecms.co/docs/properties/conditional_fields

Let me know if that works

**Comment by ciriousjoker** [comment]
I didn't even know about the builders so far, code is way cleaner now :)
