### ISSUE TITLE
How to add custom functionality

### ISSUE THREAD

**Issue by LaiArturs** [firecmsco/firecms#546]
Hello!

I would like to know what is the best way to add custom functionality to firecms page?
I would like to trigger and monitor a Vercel deployment which is achieved by simple "fetch get" call. So I would like some place to put custom react component and I don't want to recreate whole home page.

Any advise?

**Comment by fgatti675** [comment]
Check this :)
https://firecms.co/docs/navigation/custom_top_level_views
