### ISSUE TITLE
Removing additional header space in form view

### ISSUE THREAD

**Issue by faizanabidnaqvi** [firecmsco/firecms#547]
Hi there!

I was using firecms v1 for while and now trying out v2. Looks really good. :) We were using it as part of an internal tool and I am now looking into updating to v2.

The new form view is pretty good but I wish to remove this additional space on top of the title (or possibly the title as well) in the form view to reduce the scrolling needed to see the rest of the fields.

Is there a way to accomplish this at the moment?

<img width="699" alt="Screenshot 2023-09-13 at 12 32 29 PM" src="https://github.com/firecmsco/firecms/assets/5749036/bcb987f2-fe6b-4b7f-a54f-715192eb20bb">

**Comment by fgatti675** [comment]
Hi @faizanabidnaqvi 
Sorry for the late reply.
This layout is similar in V3 PRO, but with our new subscription model we offer our users to prioritise modifications like this one. Let me know if interested!
Closing the ticket for now
