### ISSUE TITLE
BUG: spreadChildren for propertyBuilder is not working correctly!

### ISSUE THREAD

**Issue by mvarchdev** [firecmsco/firecms#552]
When you use function, builder for property and you enable spreadChildren, it will show columns, but not Preview fields - then to the right it will show values of non spreadChildren values

## How to reproduce?

This property works normally:
```tsx
testProperty: {
                dataType: "map",
                spreadChildren: true,
                properties: {
                    testInside: {
                        name: "Test inside 1",
                        dataType: "string"
                    },
                    testInsideSecond: {
                        name: "Test inside 2",
                        dataType: "string"
                    }
                }
            },
```
<img width="1350" alt="Screenshot 2023-09-19 at 17 21 50" src="https://github.com/firecmsco/firecms/assets/12719761/5598983e-fe52-479c-a5f9-1b2e7b64f014">

This property is not working normally:
```tsx
testProperty: ()=>({
                dataType: "map",
                spreadChildren: true,
                properties: {
                    testInside: {
                        name: "Test inside 1",
                        dataType: "string"
                    },
                    testInsideSecond: {
                        name: "Test inside 2",
                        dataType: "string"
                    }
                }
            }),
```
<img width="1337" alt="Screenshot 2023-09-19 at 17 21 02" src="https://github.com/firecmsco/firecms/assets/12719761/96955c50-c9dc-4dcc-b532-edf1415c3e77">

Currently I am trying to find bug in code, but any suggestions would be helpful!
Thanks in advance!

**Comment by mvarchdev** [comment]
I found the problem, here (https://github.com/firecmsco/firecms/blob/b9726cff13e06c99b621ebd077800ca243b3dd4a/lib/src/core/components/EntityCollectionTable/EntityCollectionTable.tsx#L303) if `collection.properties` have map object, for example address, it is not resolved. Also in `getPropertyInPath` it is not resolved.

**Comment by mudassirmaroof** [comment]
@mvarchdev @fgatti675 We are facing the same issues, when can we expect this to be merged in ?

**Comment by fgatti675** [comment]
Hi guys, this code is revamped in v3 and working fine, I encourage you to try the new version :)
