### ISSUE TITLE
`getFile` method of storage source, does not work correctly with CORS

### ISSUE THREAD

**Issue by mvarchdev** [firecmsco/firecms#557]
I think, with API it should work even when CORS on bucket is not set, reffer to screenshot:
<img width="1440" alt="Screenshot 2023-09-22 at 12 39 10" src="https://github.com/firecmsco/firecms/assets/12719761/bf700117-95a0-4650-9460-9f0e87411e59">

**Comment by fgatti675** [comment]
Hi everyone, this is related to each client specific config.
You can change your projects CORS setup following the Firebase docs:
https://firebase.google.com/docs/storage/web/download-files#cors_configuration
