### ISSUE TITLE
Page load times are extremely slow

### ISSUE THREAD

**Issue by chris-taffi** [firecmsco/firecms#564]
We are using FireCMS version `1.0.0-beta9`.
Recently we had an issue where after logging into FireCMS it took a very long time (several minutes) to load the page before anything could be displayed.
When accessing the CMS, I noticed that there were requests of the form
<https://firestore.googleapis.com/google.firestore.v1.Firestore/Listen/channel?...>
called continuously. These are polling requests to receive changes related to records on Firestore.
The first request when accessing the CMS seems to have received too much data (it took nearly 1 minute for the results to return and the response size was 29.2MB). That's what causes the CMS to load for a long time before being able to display anything.

![image](https://github.com/firecmsco/firecms/assets/107380131/5bbb2b90-1279-4536-b7b2-a6a17154f627)

It wasn't slow like that before. It may be because we have recently had a rapid increase in the number of user records. Currently, we have nearly 190K users, at some point every minute there will be about 20-30 new users created.
Please suggest a solution for this case.
Thank you.

**Comment by fgatti675** [comment]
Hi, did you disable pagination by any chance?

**Comment by chris-taffi** [comment]
@fgatti675 We do not set any configuration regarding pagination.

**Comment by fgatti675** [comment]
Hi Chris, I would encourage you to migrate to version 2.1, or at least 1.0 (since you are still in 1 beta).
If you need further assistance please reach us at hello@firecms.co :)
