### ISSUE TITLE
Collection group view shows 'Add' button

### ISSUE THREAD

**Issue by faizanabidnaqvi** [firecmsco/firecms#572]
Hi!

In collection group view, the add entity button shows. When using the button to create an entity, the entity will get saved in a root collection with the subcollection's name. This can cause issues, for instance, if another root collection exists by the same name. 

We can probably disable creating entities for this collection group to not show it but it can cause issues if unsuspecting dev/users try to use it.

**Comment by fgatti675** [comment]
Fixed in version `2.2.0-pre`. Could you confirm this is working?

**Comment by faizanabidnaqvi** [comment]
I can confirm that this is working, that is, the add button doesn't show in the collection group now. :)
