### ISSUE TITLE
Text search doesn't load fully by the time loading has ended and other search issues

### ISSUE THREAD

**Issue by faizanabidnaqvi** [firecmsco/firecms#576]
Hi there

The text search can be buggy sometimes. I noticed several issues. Some of them I can't recreate easily.

But this one is reproducible. When searching, firecms shows a loading state besides the search which is handy to know that search is ongoing. However, sometimes the loading animation will end and show some extra entities not part of the search. If we wait a couple of seconds, the correct entities will appear but since the loading animation ended, there is no way to know that the search is not complete yet. This can be a problem for users because they don't know that they are supposed to wait for search to complete.

Here is a recording from the demo site:

https://github.com/firecmsco/firecms/assets/5749036/1330e568-6c90-480e-b006-1d9c800e8074

Notice that the proper entity appears in the end after waiting a couple of seconds (after the loading ended).

Other issues I noted that are not easy to reproduce:
- Typing in a search loads forever sometimes. To fix this we must refresh the browser window
- When searching large collections (1000+ entities), the search box lags when typing in

**Comment by faizanabidnaqvi** [comment]
When logging hits returned from algolia, I noted that when typing in the query text the results of an incomplete query text will be returned after typing in the full query. 

For example, when typing in the term `lastbilen`, the log shows this in sequence. So the results for `last` are returned after completing the full term `lastbilen`. 

```
la hits: 463
las hits: 66
l hits: 875
lastb hits: 64
lastbilen hits: 64
last hits: 417
```

**Comment by faizanabidnaqvi** [comment]
Hi there!

I noted that firecms 2.2.0 has some fixes for search but the issues mentioned here still occur. We are unable to use v2 in production due to this reason as search is important for our use case. We manage 1000+ content docs in some collections. We are still using 1.0.3 for now.

I just wanted to inform you and will be thankful if you can look into it. :)

**Comment by fgatti675** [comment]
Hi @faizanabidnaqvi 
As I also said in the other ticket, text search has been revamped in v3, and we are also introducing local text search which might help in that use case :)
