### ISSUE TITLE
Inconsistent search results

### ISSUE THREAD

**Issue by faizanabidnaqvi** [firecmsco/firecms#577]
This could be closely related to #576.

Search results can be inconsistent sometimes. The same search search that executes first might give incorrect results first time when typing in the search bar (note that it doesn't 'fix' after waiting a while too). But when typing again, it might give correct results later.

Here is a video of searching for a term which gives too many results at first but then after removing and adding characters, it gets the correct results.

https://github.com/firecmsco/firecms/assets/5749036/4bdb6019-95e5-4a9d-9960-515cd9e23d23

Notice that at 7s in this video, it shows too many results for the same term and when deleting and adding back characters (at 15s) it shows only some (the correct result).

**Comment by fgatti675** [comment]
Hi, text search was revamped in V3. Feel free to reopen if there still any issues!
