### ISSUE TITLE
Text search keeps loading although algolia has returned hits

### ISSUE THREAD

**Issue by faizanabidnaqvi** [firecmsco/firecms#578]
Also mentioned in #576. Here are more details on that.

After executing several searches, text search at some point stops working even though hits are returned from algolia.

https://github.com/firecmsco/firecms/assets/5749036/f326104c-b16c-4d50-8984-c1af0493fcc9

Notice that search keeps loading for any term. At this point, I logged the results from performTextSearch function and it did return the hits. So maybe this has something to do with fetching the entities from firestore.

This gets fixed when refreshing the window and searching again, but it will start happening again when searching a couple of times.

**Comment by fgatti675** [comment]
Thank you for reporting!
Text search has been revamped in version 3 and we are not planning to back port it to v2.
Feel free to try the new version :)
