### ISSUE TITLE
Access Control Issue: Inconsistent Login Blocking

### ISSUE THREAD

**Issue by DanishMehmoodTintash** [firecmsco/firecms#585]
### Issue Description
I've implemented access control checks in the authenticator function. If a user without access attempts to log in, the authenticator correctly blocks the user. However, if a valid user with access logs in after an unauthorized user in the same browser session, the login page displays an error stating the user is not allowed to access, even though the valid user is successfully logged in behind the scenes. Upon refreshing the page, the user gains access without the need to log in again.

### Steps to Reproduce
1. Log in with an unauthorized user.
2. Log in with an authorized user without refreshing/closing the browser or session.
3. Observe the error on the login page.
4. Refresh the page and notice the access is granted without re-entering credentials.

### Expected Behavior
The login page should accurately reflect the current authorized user's status without requiring a page refresh. It should immediately grant access to authorized users and block unauthorized users.

### Additional Information
- Framework/Language Used: [e.g., FireCMS, Typescript, React]
- Browser: [e.g., Chrome, Safari]

**Comment by OskarGroth** [comment]
Probably related issue: when logging in with OAuth, I get the popup and sign in but nothing happens on the login page. I have to force refresh to get into the dashboard.

**Comment by fgatti675** [comment]
This should be fixed in version `2.2.1` :)

**Comment by DanishMehmoodTintash** [comment]
@fgatti675 When do are planning to release version 2.2.1?
