### ISSUE TITLE
Bundle size is huge

### ISSUE THREAD

**Issue by OskarGroth** [firecmsco/firecms#588]
Because the only way to import the package is via the umbrella export:

https://github.com/firecmsco/firecms/blob/029f3f641be99d6241a4ad827190e8a4ccea5cbe/lib/src/index.ts

The resulting import for just some types is huge:

<img width="313" alt="Screenshot 2023-11-08 at 11 42 22" src="https://github.com/firecmsco/firecms/assets/1417019/e5715b78-0a48-4938-890e-4141605097eb">

Any plans to address this?

**Comment by fgatti675** [comment]
Hi Oskar, Thank you for the feedback :)
FireCMS is a fairly complex app, and all the features are required in one way or another.
In version 3.0 we have removed MUI and emotion from the equation and replaced it with tailwind which already helps.
We are working on dynamic lazy imports which will also be beneficial for code splitting.
