### ISSUE TITLE
Disabling navigation drawer expansion

### ISSUE THREAD

**Issue by OskarGroth** [firecmsco/firecms#589]
![ux](https://github.com/firecmsco/firecms/assets/1417019/28921af2-0ccc-407e-a3c6-4336886f4699)

The UX for the navigation drawer is pretty bad, as it displaces the whole menu vertically and just adds unnecessary animation for a common interaction. I also don't need a 200x200px size logo.

I'd like to disable the expansion feature altogether and just always keep it expanded/minimized. Is there a way to achieve that?

**Comment by petost** [comment]
Try
`autoOpenDrawer:false`
https://firecms.co/docs/navigation/app_config

Is this what you are looking for?

**Comment by OskarGroth** [comment]
I'm aware of that flag, but it doesn't fix the issue. It would be better if there was a flag for changing the mode of the sidebar to simply be static open/closed. I'm trying to achieve it via a custom app but it is quite tricky since the drawer is located inside the Scaffold component.

**Comment by fgatti675** [comment]
Hi @OskarGroth 
Sorry for the late reply.
We are reworking the base components to make them more customizable, and we are taking this input. Thanks!

**Comment by fgatti675** [comment]
Hi, in version 3 it is now possible to control the state of the drawer via the `useApp` hook.
Available in the latest releases. It is also possible to replace the drawer completely:
https://firecms.co/docs/pro/main_components#useapp-hook
