### ISSUE TITLE
Access to entity on permissions builder (outdated docs)

### ISSUE THREAD

**Issue by andreassh** [firecmsco/firecms#592]
In the [docs](https://firecms.co/docs/collections/permissions) it states that you can access the current entity in the permissionsBuilder.
This seems outdated according to the types.d definitions. Docs says that you the permissionsBuilder is called with following properties:

``` 
{
    entity,
    path,
    user,
    authController,
    context
}
```

But types says its called with: 
``` 
{ 
  pathSegments, 
  user, 
  collection,
  authController 
} 
``` 
Which seems to be right.

But what can be done do make permissions dependent on properties on and entity in v. 2.2.0? 
E.g. if you want do disable create, depending on an entity prop?

**Comment by fgatti675** [comment]
Sorry for the late reply. `entity` is there in permissions builder in v3 :)
