### ISSUE TITLE
Editing a an array of references in a side panel triggers the document to be updated twice.

### ISSUE THREAD

**Issue by iavina** [firecmsco/firecms#596]
Editing a an array of references in a side panel triggers the document to be updated twice.
However clicking the arrow on an entity to enter the entity's side panel, and then updating the array from there, correctly only triggers once.
Has someone had this issue? This is how I'm building my property
```
        categories: buildProperty((entity: any) => ({
            name: "Categories",
            dataType: "array",
            of: {
                dataType: "reference",
                path: entity.path.replace("Products", "Categories"),
                previewProperties: ["name"]
            }
        })),
```

**Comment by fgatti675** [comment]
This should be fixed in latest versions
