### ISSUE TITLE
Default value on array of maps properties

### ISSUE THREAD

**Issue by nkulic** [firecmsco/firecms#599]
### What is the current behavior?
When using enumValues in a map property which is inside array (of) property, default enum value is not set.

### What is the expected behavior?
Default enum value should be set.

### Reproduction steps
I have created a repo with starter template and configured collection for reproduction of this issue:
- https://github.com/nkulic/firecms-default-enumValues-bug

Or manually create project with firecms template and modify collection config:
1. Use starter template to create fireCMS project:
```
yarn create firecms-app
or
npx create-firecms-app
```
2. Set firebaseConfig to valid firebase project
3. Modify collection:
```js
export const showcaseCollection = buildCollection({
  path: "showcase",
  customId: false,
  icon: "ShowChart",
  name: "Showcase",
  hideIdFromForm: true,
  properties: {
    featuredProducts: buildProperty({
      dataType: "array",
      name: "Featured products",
      of: {
        name: "Featured product",
        dataType: "map",
        properties: {
          size: buildProperty({
            dataType: "string",
            name: "Size",
            defaultValue: "smallVertical",
            enumValues: {
              largeVertical: { id: "largeVertical", label: "Large vertical" },
              smallVertical: { id: "smallVertical", label: "Small vertical" },
            },
          }),
          title: {
            name: "Product",
            dataType: "string",
          },
        },
      },
    }),
  },
});
```

### Package versions used
- "react": "^18.2.0"
- "react-dom": "^18.2.0"
- "firecms": "^2.0.0"

**Comment by fgatti675** [comment]
This should be fixed in the latest 3.0 versions :)
