### ISSUE TITLE
Email login

### ISSUE THREAD

**Issue by gerontius** [firecmsco/firecms#600]
I've installed firecms on firebase. It's all working good except I can't see any other option except a Google login. Email + password Auth is enabled on the firebase project. I installed using the npx create command outlined in the quick start docs. I saw a thread on here suggesting that the options have been automatic for a while.

**Comment by fgatti675** [comment]
Hi @gerontius !
What version of FireCMS are you using?
Or are you accessing through app.firecms.co ?

**Comment by gerontius** [comment]
hi @fgatti675 
Self hosted. Im not 100% sure but i installed using npx create-firecms-app which installed create-firecms-app@2.0.0.

Thanks

**Comment by gerontius** [comment]
Hi @fgatti675 

Any further thoughts on this. Login with Google could be problematic for my use case.

**Comment by fgatti675** [comment]
Hi, in the version you are using there is a `signInOptions` prop you can use to define the different login options:

```
    return <FirebaseCMSApp
        name={"My Online Shop"}
        authentication={myAuthenticator}
        allowSkipLogin={true}
        plugins={[dataEnhancementPlugin]}
        signInOptions={[
            "password",
            "google.com"
            // 'anonymous',
            // 'phone',
            // 'facebook.com',
            // 'github.com',
            // 'twitter.com',
            // 'microsoft.com',
            // 'apple.com'
        ]}
        textSearchController={textSearchController}
        firestoreIndexesBuilder={firestoreIndexesBuilder}
        logo={logo}
        collections={(params) => collections}
        views={customViews}
        firebaseConfig={firebaseConfig}
        onFirebaseInit={onFirebaseInit}
        toolbarExtraWidget={githubLink}
        LoginView={CustomLoginView}
        onAnalyticsEvent={onAnalyticsEvent}
    />;

```
