### ISSUE TITLE
Datas are not updated , have to recreate whole collection to add to fireCMS

### ISSUE THREAD

**Issue by derikesh** [firecmsco/firecms#603]

**Comment by fgatti675** [comment]
Hi! can you elaborate?

**Comment by qsalatiel** [comment]
Hi, I had the a similar problem, on v3 I already had a collection created before integrating with firecms after opening the project on firecms the collection that I had didn't show up on the collection list it only showed after I deleted and created again on firebase directly

**Comment by fgatti675** [comment]
Hi, the original post was deleted, closing this since I am not sure what the issue was
