### ISSUE TITLE
Issue with CLI in virtual instance in Cloud

### ISSUE THREAD

**Issue by marianmoldovan** [firecmsco/firecms#605]
Bug with the CLI in an AWS Linux EC2 Instance.

Node ver: 18

/home/ec2-user/.config/yarn/global/node_modules/@firecms/cli/build/commands/init.js:56
        console.log("You are logged in as", currentUser["email"]);

<img width="1129" alt="Bug in firecms cli" src="https://github.com/firecmsco/firecms/assets/1479084/50d17fa5-6fd6-4bc1-ba84-d00bc6f7998b">

**Comment by marianmoldovan** [comment]
Has been solved in ver alpha.61

**Comment by fgatti675** [comment]
Right, I was just fixing it while you opened the ticket 😄
