### ISSUE TITLE
How to delete a project or revoke FireCMS access to the Firebase project

### ISSUE THREAD

**Issue by salatielsql** [firecmsco/firecms#606]
I created a test project on Firebase and then created linked the project to the FireCMS app. After that I tried:

- Go to my Google Account dashboard and revoked the firecms access from there
- Find a delete project button on the FireCMS web app

How can I delete the project or better revoke FireCMS access to my Firebase project?

**Comment by marianmoldovan** [comment]
Hello @salatielsql, if you delete the service account from your Google Cloud Project that will get the job done. If you go to IAM, you will see of user of this type: `firecms@PROJECT_ID.iam.gserviceaccount.com`. We don't really access the data, when you get in the app, you are using your own credentials to do so via OAuth 2.0.

Alternatively, if you want to delete all the resources related to the project. Send us an email at hello@firecms.co or ping us at Discord. We can delete everything on our side if you desire it.
