### ISSUE TITLE
Cannot start the app locally

### ISSUE THREAD

**Issue by tomlai19852004** [firecmsco/firecms#609]
I run into the following the instruction to run yarn dev

✘ [ERROR] Failed to resolve entry for package "/Users/hosumlai/Documents/projects/ohmyink/firecms/oh-my-ink/node_modules/date-fns/locale". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-pre-bundle]

<img width="1501" alt="Screenshot 2024-01-17 at 6 09 20 AM" src="https://github.com/firecmsco/firecms/assets/2049942/7ed0e01a-1c47-4c05-b681-3e57f7a86eb7">

**Comment by fgatti675** [comment]
Hi, could not reproduce this in the latest versions.
I think there was some importing error in a previous one.
