### ISSUE TITLE
FireCMS - Cannot create a collection or a field

### ISSUE THREAD

**Issue by Pratham5236** [firecmsco/firecms#610]
Hi there,
I've been meaning to try out the FireCMS because it looks promising. But when I go to create a new Collection or import an existing one from my Firebase project, the 'OK' or the 'Create' button seems to do nothing when clicked.
Is this a known issue or something that's planned to the future to be fixes? Because I cannot use the service at all without this.
![image](https://github.com/firecmsco/firecms/assets/63796782/025f950c-f8b4-4f74-a2a5-b7b9f5877759)

Steps to reproduce:
1) Made a new FireCMS account
2) Choose a Firebase project
3) Try creating a new collection or add a new field

Any help would be appreciated

**Comment by fgatti675** [comment]
Thanks for the report! should be fixed now :)

**Comment by Pratham5236** [comment]
Thanks for the quick response!
I just checked and it had started working. I added 2 fields, but when trying to add the third field, I'm encountering the same problem again

**Comment by fgatti675** [comment]
Exactly what field did you add 3rd?

**Comment by Pratham5236** [comment]
I was trying to add files, but since that Didn't work I tried a normal text again and that couldn't be added either
