### ISSUE TITLE
Cannot access 'a10' before initialization

### ISSUE THREAD

**Issue by VisetDev** [firecmsco/firecms#613]
This happen only en local dev:
I have no react knowledge.

When selecting a document from the collection:

![image](https://github.com/firecmsco/firecms/assets/108474478/0eb168f2-f118-4aa2-bb85-ec748ade8da9)

```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
Check the render method of `SlotClone`.
```

after trying to delete a newly created element:

![image](https://github.com/firecmsco/firecms/assets/108474478/45d09dca-4bca-4fcf-8340-506c8688ea85)

```ReferenceError: Cannot access 'a10' before initialization```

**Comment by fgatti675** [comment]
Hi Visdet, that is a minified error, but I think it has been already solved in the latest beta version, give it a try :)

**Comment by VisetDev** [comment]
I'm using "firecms": "^3.0.0-alpha", is that correct?

**Comment by fgatti675** [comment]
Update to `^3.0.0-beta`  and run `yarn` and it should be fixed :)
