### ISSUE TITLE
Bug - Selection page opens when trying to view the edit panel

### ISSUE THREAD

**Issue by Brackyt** [firecmsco/firecms#620]
There is a weird bug happening when trying to edit a document in FireCMS.
If you have a field that is a list of references and you click on it to edit the list (selection panel), close it and try to open the edit page for the document (the arrow thing), it actually shows the previous selection page for the field that you opened, and it also goes out of the screen.

It opens the wrong page and it should not go out of screen.

<img width="1276" alt="firecms-panel-bug" src="https://github.com/firecmsco/firecms/assets/60280126/09e549a0-4b8b-42d2-a728-362e416df12d">

**Comment by fgatti675** [comment]
Late reply, this was fixed a bunch of versions ago :)
