### ISSUE TITLE
Drag and drop order function

### ISSUE THREAD

**Issue by danieljancar** [firecmsco/firecms#622]
Hey, I've been trying to use a order for documents where each document has a field `order` with a number inside of it to define how the documents should be ordered in the frontend. Now I was wondering if there's a solution for changing the order of documents and sort/update the `order` field on each document appropriately?
Thanks for your help. 😄

**Comment by fgatti675** [comment]
Hi Daniel, this is not straightworward. We have implemented something similar but using backend functions in clients projects. When ever an order changes, we update the rest of the docs accordinly

**Comment by fgatti675** [comment]
By the way, we can help you better in discord!
