### ISSUE TITLE
Hide Document ID on regular reference property

### ISSUE THREAD

**Issue by VisetDev** [firecmsco/firecms#623]
when I add a reference property it shows document ID regardless it is not set on 'previewProperties'.

![image](https://github.com/firecmsco/firecms/assets/108474478/bb27a953-49f3-4a4e-922a-1b13cb8311a9)

this works in case of array pointing to collection:

![image](https://github.com/firecmsco/firecms/assets/108474478/cc7a9b26-9b13-4ae2-b269-8816bd25b599)

Id should be shown only by default (if no "previewProperties" are assigned)

**Comment by fgatti675** [comment]
There is now a `includeId` prop in reference properties :)

**Comment by VisetDev** [comment]
Thanx @fgatti675 but it does not seems to work:

```
elements: buildProperty({
      dataType: "array",
      name: "Elements",
      of: {
        dataType: "reference",
        includeId: false,
        path: "/visets",
        previewProperties: ["title"],
      }
    }),
```


![image](https://github.com/user-attachments/assets/4b33a519-d7b5-41b5-be12-2e991bb92845)

both in local and cloud...


```
 "dependencies": {
    "@firecms/cloud": "3.0.0-beta.8",
    "firebase": "^10.9.0",
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
  },
```
