### ISSUE TITLE
Crash - Impossible to insert a date field in a collection

### ISSUE THREAD

**Issue by CarloTerracciano** [firecmsco/firecms#631]
Impossible to insert a date field into a collection because **_app.firecms.co_** does not allow any action to be taken. 

<img width="346" alt="Screenshot 2024-03-15 at 23 21 23" src="https://github.com/firecmsco/firecms/assets/21176829/04884fca-0a27-4770-ad3a-b103dd72fa05">

The console reports the following errors:

<img width="529" alt="Screenshot 2024-03-15 at 23 19 28" src="https://github.com/firecmsco/firecms/assets/21176829/37b53922-3e2d-4d27-afa4-00a6c23ea8f3">

**Comment by fgatti675** [comment]
Thanks Carlo, a fix was already on the way and it is now deployed.
Feel free to refresh the app and try again :)
