### ISSUE TITLE
Filter and Sort for different keys

### ISSUE THREAD

**Issue by nivlempert1** [firecmsco/firecms#636]
Hi there,

I've been trying to implement filtering and sorting with different keys, but I'm facing a challenge. Whenever I try to select one, it toggles off the other in the UI. 

In my case, I got two keys- "id" and "created", I need to filter "id" by equality and sort by "created" date.

I followed the instructions in "Multiple filters in collection views," which involved adding firestoreIndexesBuilder and implementing the indexes in Firestore. However, despite these efforts, the UI won't allow me to select both filter and sort simultaneously.

The only workaround I found is hard-coding initialFilter and initialSort, but that's not flexible.

Do you have any suggestions on how I can achieve this functionality seamlessly?

**Comment by fgatti675** [comment]
Hi, what version of FireCMS are you using?

**Comment by nivlempert1** [comment]
tried it in both v2.2 and the latest v3

**Comment by fgatti675** [comment]
So you deployed to FireCMS Cloud?

**Comment by nivlempert1** [comment]
tried it locally

**Comment by fgatti675** [comment]
got it, can you post your code so I try to reproduce it?

**Comment by nivlempert1** [comment]
I just followed that guide: https://firecms.co/docs/collections/multiple_filters
The thing is I can't see any comment about sorting + filtering.
Is that supposed to work?

**Comment by fgatti675** [comment]
It is probably working as expected. Could you try doing your requested query in a script and see if it works?

**Comment by nivlempert1** [comment]
Thats a video of my problem- I can only choose sort or filter, not both of them.
Does it even supposed to work for both of them?
https://github.com/firecmsco/firecms/assets/29779843/a29050b1-45a2-4038-a1b3-2fc03c7537fd

**Comment by fgatti675** [comment]
Hi! we have done an update in the latest version.
The package name has changed from `firecms` to `@firecms/cloud` and the version is `3.0.0-beta.4`.
Give it a try, now it should work as you expect

**Comment by nivlempert1** [comment]
Wow thank you so much! you solved it!
