### ISSUE TITLE
Warning: Function components cannot be given refs.

### ISSUE THREAD

**Issue by VisetDev** [firecmsco/firecms#637]
When trying to select any element from any collection I got:

Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `SlotClone`.
    at o (http://localhost:5001/node_modules/.vite/deps/@firecms_cloud.js?v=b4d01b98:39322:12)
    at http://localhost:5001/node_modules/.vite/deps/@firecms_cloud.js?v=b4d01b98:5890:11
    at http://localhost:5001/node_modules/.vite/deps/@firecms_cloud.js?v=b4d01b98:5867:11
    at http://localhost:5001/node_modules/.vite/deps/@firecms_cloud.js?v=b4d01b98:5959:13
[...]

The warning arises when selecting the checkbox:

![image](https://github.com/firecmsco/firecms/assets/108474478/39e25f16-564e-4d07-9168-fb5fb5f2a84e)

It breaks the view. next time I open the collection, state does not reflects selected and the table looks wrong:

![image](https://github.com/firecmsco/firecms/assets/108474478/44711c3a-0cdc-4e66-8f1c-ce901d636af0)

**Comment by fgatti675** [comment]
Could not reproduce in latest version!
