### ISSUE TITLE
[Question] Is FireCMS Cloud mandatory?

### ISSUE THREAD

**Issue by ludovicroland** [firecmsco/firecms#647]
Hi,

For a personal project, I used the very first version of FireCMS. It was awesome. 

In the context of a new personal project, I tried to create a project with version 3. But in the creation process, I am forced to connect to Google and give rights to a FireCMS application. This is not the case if I use version 2.

If I try to create a project through FireCMS Cloud on a self hosted project, I cannot bypass the subscription to chat GPT. So I am totally lost :(

With version 3 of FireCMS, are we forced to use FireCMS Cloud as it seems to be the case? Can't we continue to use FireCMS as a "framework" to generate a project, configure it ourselves and host it on Firebase Host ourselves?

Thank you in advance for your answer. I am not sure if I have understood how much the Cloud version of FireCMS becomes mandatory?

Regard

**Comment by fgatti675** [comment]
Hi @ludovicroland ! Thanks for reaching out.
You can use FireCMS as a framework in the PRO version (it is very similar in practice to V2, but has a ton of new features)
https://firecms.co/pro
You can get started completely for free, but you need to acquire a license if would like to use it further.
Feel free to join our discord or reach us at hello@firecms.co if you need any assistance!
https://discord.gg/fxy7xsQm3m

**Comment by ludovicroland** [comment]
Hello @fgatti675 

Thank you for your answer!

I tried to create a project using `yarn create firecms-app --pro`

But it fails with the following message:
```
You are logged in as XXXX@gmail.com
✔ Loading your projects
No FireCMS projects found
error Command failed.
Exit code: 1
Command: /opt/homebrew/bin/create-firecms-app
Arguments: --pro
Directory: /Users/mac-LROLAN03/Documents/workspace/my-books-backend
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

Does it mean that I need to create a project on FireCMS Cloud even if I would like to use it as the version 2?

**Comment by fgatti675** [comment]
Nope! Sorry about that. 
We have fixed that error in the latest canary release.
You can try it out with:
`npx create-firecms-app@^3.0.0-canary.54 --pro`
or
`yarn dlx create-firecms-app@3.0.0-canary.54 --pro`
