### ISSUE TITLE
How to force relogin into the CLI?

### ISSUE THREAD

**Issue by ludovicroland** [firecmsco/firecms#648]
Hello,

I am trying to create a new project using `yarn create firecms-app`.

Unfortunately, it failed :

```
yarn create v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Installed "create-firecms-app@3.0.0-beta.6" with binaries:
      - create-firecms-app
[#########################################################################################################################################################################] 207/207
 ___ _          ___ __  __ ___
| __(_)_ _ ___ / __|  \/  / __|
| _|| | '_/ -_) (__| |\/| \__ \
|_| |_|_| \___|\___|_|  |_|___/

Welcome to the FireCMS CLI 🔥

You are logged in as XXXX@gmail.com
✖ Error loading projects
Error getting projects {
  message: 'Google Cloud token has invalid format',
  code: 'google-cloud-token-invalid',
  data: {}
}
error Command failed.
Exit code: 1
Command: /opt/homebrew/bin/create-firecms-app
Arguments:
Directory: /Users/mac-XXXXX/Documents/workspace/my-backend
Output:
```

How to force a re-login in order to refresh/update the google cloud token?

I have tried to execute `yarn create firecms-app login` like suggested into the issue [634](https://github.com/firecmsco/firecms/issues/634) but it does not work.

Thank you for your help.

**Comment by ludovicroland** [comment]
It was possible using `npx create-firecms-app login` instead of `yarn`.

**Comment by fgatti675** [comment]
Glad you managed! 
In the next beta version you will be able to just install `firecms` as a CLI command

**Comment by fgatti675** [comment]
BTW, please join our Discord or reach us at hello@firecms.co if you would like to discuss the pricing of FireCMS PRO, since you are a long time user :)
