### ISSUE TITLE
2.0 Docs no longer load

### ISSUE THREAD

**Issue by sambrannon** [firecmsco/firecms#655]
Not able to find/access documentation for version 2 docs anymore. The docs header version switcher no longer functions and is stuck on `3.0.0-BETA`.

Similarly, I can no longer access the 2.0 docs direct URL (https://firecms.co/docs/2.0.0/)

Maybe a hydration issue? Seeing a lot of those in my console that point to [the unminified error](https://react.dev/errors/418?invariant=418) indicating as much...

<img width="751" alt="image" src="https://github.com/user-attachments/assets/3f010c2c-2a02-4d7f-b2eb-d660f27cc072">

**Comment by fgatti675** [comment]
They are back :)
