### ISSUE TITLE
React or Javascript SDK

### ISSUE THREAD

**Issue by ohabash** [firecmsco/firecms#660]
If one exists -- i apologize new here. Is there an SDK for accessing the data. Or the recommended way is to use firebase?

**Comment by fgatti675** [comment]
Hi, sorry for the late reply. If you are building an app outside FireCMS we recommend using the Firebase SDKs.
Within FireCMS, you can either use the Firebase SDKs, or the internal components via `useDataSource` or `useStoragesource` which talk to those SDKs, or whatever data source you specified.
Best,
